Add LTI display name
arpitgandhi-xoriant/lti-params-api pull request #15
Opened 2022-11-23 10:44 UTC by RiteshChouhan21

@dcadams please review, this PR will show lti display name for all the blocks.

2022-11-24 07:41 UTC, RiteshChouhan21 commented
@dcadams item's order is updated.

2022-11-29 20:02 UTC, dcadams commented
I made these changes on my Tutor devstak and they look good.

:+1:

2022-12-05 14:57 UTC, dcadams requested changes
Looks good. Just a couple of nits.

2022-12-06 09:47 UTC, arpitgandhi-xoriant commented on lti_params_api/patch/course_experience_utils_custom.py
>              'type',
Done

2022-12-06 09:47 UTC, arpitgandhi-xoriant commented on tests/tests.py
> +        self.assertIn('i4x://edX/100/lti_advantage_consumer/knowledge_check', data['block_key'])
Done

2022-12-06 15:51 UTC, dcadams approved these changes
:+1: 
Please squash and merge.

2022-12-07 07:03 UTC, arpitgandhi-xoriant commented
Squashed and merged into master.

2022-12-07 07:03 UTC, closed without merging